# yaml 配置实例
version: '3.9'

networks:
  default:
    external: true
    name: redis_server_default

services: 
  redis_sentinel_1:
    image: redis:latest
    container_name: redis_sentinel_1
    restart: always
    privileged: true
    environment:
      TZ: "Asia/Shanghai"
      LANG: "en_US.UTF-8"
    ports: 
      - "27001:26379"
    env_file: 
      - ../config/redis.env
    command: /bin/bash -c "redis-sentinel /opt/redis/deploy/config/redis-sentinel.conf"
    volumes:
      - ./deploy/sentinel_1/data:/opt/redis/deploy/data
      - ./deploy/sentinel_1/logs:/opt/redis/deploy/logs
      - ./deploy/sentinel_1/config:/opt/redis/deploy/config

  redis_sentinel_2:
    image: redis:latest
    container_name: redis_sentinel_2
    restart: always
    privileged: true
    environment:
      TZ: "Asia/Shanghai"
      LANG: "en_US.UTF-8"
    ports: 
      - "27002:26379"
    env_file: 
      - ../config/redis.env
    command: /bin/bash -c "redis-sentinel /opt/redis/deploy/config/redis-sentinel.conf"
    volumes:
      - ./deploy/sentinel_2/data:/opt/redis/deploy/data
      - ./deploy/sentinel_2/logs:/opt/redis/deploy/logs
      - ./deploy/sentinel_2/config:/opt/redis/deploy/config

  redis_sentinel_3:
    image: redis:latest
    container_name: redis_sentinel_3
    restart: always
    privileged: true
    environment:
      TZ: "Asia/Shanghai"
      LANG: "en_US.UTF-8"
    ports: 
      - "27003:26379"
    env_file: 
      - ../config/redis.env
    command: /bin/bash -c "redis-sentinel /opt/redis/deploy/config/redis-sentinel.conf"
    volumes:
      - ./deploy/sentinel_3/data:/opt/redis/deploy/data
      - ./deploy/sentinel_3/logs:/opt/redis/deploy/logs
      - ./deploy/sentinel_3/config:/opt/redis/deploy/config

