# yaml 配置实例
version: '3.9'
services: 
  redis-singleton:
    image: redis:latest
    container_name: redis-singleton
    restart: always
    privileged: true
    environment:
      TZ: "Asia/Shanghai"
      LANG: "en_US.UTF-8"
    ports: 
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file: 
      - ../config/redis.env
    command: /bin/bash -c "redis-server /opt/redis/deploy/config/redis-server.conf --port ${REDIS_PORT} --requirepass ${AUTH_REDIS}"
    volumes:
      - ./deploy/data:/opt/redis/deploy/data
      - ./deploy/logs:/opt/redis/deploy/logs
      - ./deploy/config:/opt/redis/deploy/config
