# yaml 配置实例
version: '3.9'
services: 
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      TZ: "Asia/Shanghai"
      LANG: "en_US.UTF-8"
    ports: 
      - "3306:3306"
      - "33060:33060"
