FROM quay.io/centos/centos:stream9

ENV TZ Asia/Shanghai

RUN set -xe \
    && cat /etc/redhat-release \
    && yum -y update \
    && yum -y upgrade \
    && yum -y install git wget passwd \
    && yum -y install openssh openssh-server openssh-clients \
    && ssh-keygen -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N '' \
    && ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N '' \
    && ssh-keygen -t dsa -f /etc/ssh/ssh_host_ed25519_key  -N '' \
    && /bin/echo 'PermitRootLogin yes' > /etc/ssh/sshd_config.d/user.conf \
    && /bin/echo 'root:1234' | chpasswd \
    && /bin/echo -e "LANG=\"en_US.UTF-8\"" > /etc/default/local \
    && /usr/sbin/sshd

ENTRYPOINT ["/usr/sbin/init"]
CMD ["systemctl"]
